run:
	time uv run python3 main.py
get_cities:
	time uv run python3 get_cities.py
get_movies:
	time uv run python3 get_movies.py
get_general_stats:
	time uv run python3 get_general_stats.py
get_stats_cities:
	time uv run python3 get_stats_cities.py
footballer_data:
	time uv run python3 footballer_data.py
get_footballer_stats:
	time uv run python3 get_footballer_stats.py
format:
	uv run ruff format

