kafka-flink:
	docker compose up
manual_input:
	uv run python3 manual_input.py
streaming:
	uv run python3 start_streaming.py
analysis:
	uv run python3 analysis.py
analysis_table_api:
	uv run python3 analysis_table_api.py
analysis_stream_string:
	uv run python3 analysis_stream_string.py
format:
	uv run ruff format