kafka:
	docker compose up
manual_input:
	uv run python3 manual_input.py
streaming:
	uv run python3 start_streaming.py
analysis:
	uv run python3 analysis.py
test2:
	uv run python3 test2.py
format:
	uv run ruff format